#!/usr/bin/env python3
"""Writes sample_movies.json: hand-entered placeholder metadata for ~90 titles from
the watch history, used only until the enrichment step produces real TMDb data.
Ratings are approximate."""
import json, pathlib
S = "Sci-Fi"; H = "Horror"; C = "Comedy"; D = "Drama"; T = "Thriller"; F = "Fantasy"
A = "Action"; M = "Mystery"; CR = "Crime"; AN = "Animation"; AD = "Adventure"; R = "Romance"; W = "War"
rows = [
 ("Videodrome",1983,[H,S],["David Cronenberg"],["James Woods","Debbie Harry","Sonja Smits"],7.0),
 ("Timecrimes",2007,[S,T],["Nacho Vigalondo"],["Karra Elejalde","Candela Fernández","Nacho Vigalondo"],6.9),
 ("Midnight Special",2016,[S,D],["Jeff Nichols"],["Michael Shannon","Joel Edgerton","Kirsten Dunst","Adam Driver"],6.6),
 ("Hunt for the Wilderpeople",2016,[C,AD,D],["Taika Waititi"],["Sam Neill","Julian Dennison","Rima Te Wiata"],7.5),
 ("Beyond the Black Rainbow",2010,[S,H],["Panos Cosmatos"],["Michael Rogers","Eva Bourne"],5.9),
 ("Mandy",2018,[H,A,T],["Panos Cosmatos"],["Nicolas Cage","Andrea Riseborough","Linus Roache"],6.5),
 ("Something in the Dirt",2022,[S,T,C],["Justin Benson","Aaron Moorhead"],["Justin Benson","Aaron Moorhead"],6.4),
 ("The Endless",2017,[S,H,M],["Justin Benson","Aaron Moorhead"],["Justin Benson","Aaron Moorhead","Callie Hernandez"],6.5),
 ("Spring",2014,[H,R,S],["Justin Benson","Aaron Moorhead"],["Lou Taylor Pucci","Nadia Hilker"],6.4),
 ("Synchronic",2019,[S,D,T],["Justin Benson","Aaron Moorhead"],["Anthony Mackie","Jamie Dornan","Katie Aselton"],6.2),
 ("Coherence",2013,[S,T,M],["James Ward Byrkit"],["Emily Baldoni","Maury Sterling","Nicholas Brendon"],7.1),
 ("Caveat",2020,[H,T],["Damian Mc Carthy"],["Jonathan French","Leila Sykes","Ben Caplan"],6.1),
 ("Oddity",2024,[H,M],["Damian Mc Carthy"],["Carolyn Bracken","Gwilym Lee","Caroline Menton"],6.8),
 ("Bugonia",2025,[S,C,T],["Yorgos Lanthimos"],["Emma Stone","Jesse Plemons","Aidan Delbis"],7.2),
 ("Poor Things",2023,[S,R,C],["Yorgos Lanthimos"],["Emma Stone","Mark Ruffalo","Willem Dafoe"],7.7),
 ("Die My Love",2025,[D,T],["Lynne Ramsay"],["Jennifer Lawrence","Robert Pattinson","LaKeith Stanfield"],6.4),
 ("Strawberry Mansion",2021,[F,S,C],["Albert Birney","Kentucker Audley"],["Kentucker Audley","Penny Fuller","Grace Glowicki"],6.4),
 ("Ghost Stories",2017,[H,M],["Jeremy Dyson","Andy Nyman"],["Andy Nyman","Martin Freeman","Paul Whitehouse","Alex Lawther"],6.3),
 ("Lord of Illusions",1995,[H,F,M],["Clive Barker"],["Scott Bakula","Kevin J. O'Connor","Famke Janssen"],6.0),
 ("Nightbreed",1990,[H,F],["Clive Barker"],["Craig Sheffer","David Cronenberg","Anne Bobby"],6.5),
 ("The Hidden",1987,[S,A,H],["Jack Sholder"],["Kyle MacLachlan","Michael Nouri"],6.8),
 ("Matinee",1993,[C,D],["Joe Dante"],["John Goodman","Cathy Moriarty","Simon Fenton"],6.7),
 ("Explorers",1985,[S,AD,F],["Joe Dante"],["Ethan Hawke","River Phoenix","Jason Presson"],6.5),
 ("Wicked City",1987,[AN,H,S],["Yoshiaki Kawajiri"],["Yūsaku Yara","Toshiko Fujita"],6.9),
 ("Demon City Shinjuku",1988,[AN,H,F],["Yoshiaki Kawajiri"],["Hideyuki Hori","Hiroko Emori"],6.4),
 ("Perfect Blue",1997,[AN,T,M],["Satoshi Kon"],["Junko Iwao","Rica Matsumoto"],8.2),
 ("Akira",1988,[AN,S,A],["Katsuhiro Otomo"],["Mitsuo Iwata","Nozomu Sasaki"],8.0),
 ("Memories",1995,[AN,S],["Katsuhiro Otomo","Kōji Morimoto","Tensai Okamura"],["Tsutomu Isobe","Shigeru Chiba"],7.6),
 ("Ghost in the Shell",1995,[AN,S,A],["Mamoru Oshii"],["Atsuko Tanaka","Akio Ōtsuka"],7.8),
 ("Mermaid",2016,[C,F,R],["Stephen Chow"],["Deng Chao","Lin Yun","Show Lo"],6.2),
 ("Kung Fu Hustle",2004,[A,C,CR],["Stephen Chow"],["Stephen Chow","Yuen Wah","Yuen Qiu"],7.5),
 ("Journey to the West",2013,[F,AD,C],["Stephen Chow"],["Shu Qi","Wen Zhang","Huang Bo"],6.5),
 ("The Greasy Strangler",2016,[C,H],["Jim Hosking"],["Michael St. Michaels","Sky Elobar","Elizabeth De Razzo"],4.9),
 ("Masters of the Universe",1987,[F,A,S],["Gary Goddard"],["Dolph Lundgren","Frank Langella","Meg Foster","Courteney Cox"],5.4),
 ("Enter the Fat Dragon",2020,[A,C],["Kenji Tanigaki"],["Donnie Yen","Niki Chow","Teresa Mo"],6.2),
 ("Death on the Nile",2022,[M,CR,D],["Kenneth Branagh"],["Kenneth Branagh","Gal Gadot","Emma Mackey"],6.4),
 ("Murder on the Orient Express",2017,[M,CR,D],["Kenneth Branagh"],["Kenneth Branagh","Michelle Pfeiffer","Daisy Ridley","Penélope Cruz"],6.7),
 ("A Haunting in Venice",2023,[M,CR,H],["Kenneth Branagh"],["Kenneth Branagh","Michelle Yeoh","Tina Fey","Jamie Dornan"],6.6),
 ("Blithe Spirit",2020,[C,F],["Edward Hall"],["Dan Stevens","Leslie Mann","Isla Fisher","Judi Dench"],5.4),
 ("Beyond the Infinite Two Minutes",2020,[S,C],["Junta Yamaguchi"],["Kazunari Tosa","Riko Fujitani"],7.3),
 ("Prince of Darkness",1987,[H,S],["John Carpenter"],["Donald Pleasence","Jameson Parker","Lisa Blount"],6.6),
 ("In the Mouth of Madness",1994,[H,M,T],["John Carpenter"],["Sam Neill","Jürgen Prochnow","Julie Carmen"],7.0),
 ("Escape from New York",1981,[S,A],["John Carpenter"],["Kurt Russell","Lee Van Cleef","Donald Pleasence"],7.0),
 ("Big Trouble in Little China",1986,[A,C,F],["John Carpenter"],["Kurt Russell","Kim Cattrall","Dennis Dun"],7.1),
 ("The Ward",2010,[H,T],["John Carpenter"],["Amber Heard","Mamie Gummer","Danielle Panabaker"],5.7),
 ("No Country for Old Men",2007,[CR,D,T],["Joel Coen","Ethan Coen"],["Tommy Lee Jones","Javier Bardem","Josh Brolin"],7.9),
 ("Barton Fink",1991,[D,C,M],["Joel Coen","Ethan Coen"],["John Turturro","John Goodman","Judy Davis"],7.4),
 ("Burn After Reading",2008,[C,CR],["Joel Coen","Ethan Coen"],["George Clooney","Frances McDormand","Brad Pitt","John Malkovich"],6.7),
 ("The Royal Tenenbaums",2001,[C,D],["Wes Anderson"],["Gene Hackman","Anjelica Huston","Bill Murray","Owen Wilson"],7.3),
 ("Bottle Rocket",1996,[C,CR],["Wes Anderson"],["Owen Wilson","Luke Wilson","Robert Musgrave"],6.6),
 ("The French Dispatch",2021,[C,D,R],["Wes Anderson"],["Benicio del Toro","Frances McDormand","Bill Murray","Timothée Chalamet"],7.0),
 ("Asteroid City",2023,[C,D,S],["Wes Anderson"],["Jason Schwartzman","Scarlett Johansson","Tom Hanks"],6.5),
 ("The Phoenician Scheme",2025,[C,AD],["Wes Anderson"],["Benicio del Toro","Mia Threapleton","Michael Cera"],6.8),
 ("Full Metal Jacket",1987,[D,W],["Stanley Kubrick"],["Matthew Modine","R. Lee Ermey","Vincent D'Onofrio"],8.1),
 ("Barry Lyndon",1975,[D,R,W],["Stanley Kubrick"],["Ryan O'Neal","Marisa Berenson","Patrick Magee"],7.8),
 ("Seven Psychopaths",2012,[C,CR],["Martin McDonagh"],["Colin Farrell","Sam Rockwell","Christopher Walken","Woody Harrelson"],6.8),
 ("Three Billboards Outside Ebbing, Missouri",2017,[CR,D],["Martin McDonagh"],["Frances McDormand","Woody Harrelson","Sam Rockwell"],7.8),
 ("Fight Club",1999,[D,T],["David Fincher"],["Brad Pitt","Edward Norton","Helena Bonham Carter"],8.4),
 ("The Game",1997,[D,M,T],["David Fincher"],["Michael Douglas","Sean Penn","Deborah Kara Unger"],7.4),
 ("John Wick: Chapter 4",2023,[A,T,CR],["Chad Stahelski"],["Keanu Reeves","Donnie Yen","Bill Skarsgård"],7.7),
 ("John Wick: Chapter 3 - Parabellum",2019,[A,T,CR],["Chad Stahelski"],["Keanu Reeves","Halle Berry","Ian McShane"],7.4),
 ("Bill & Ted's Excellent Adventure",1989,[C,AD,S],["Stephen Herek"],["Keanu Reeves","Alex Winter","George Carlin"],6.9),
 ("Bill & Ted's Bogus Journey",1991,[C,AD,F],["Peter Hewitt"],["Keanu Reeves","Alex Winter","William Sadler"],6.3),
 ("Constantine",2005,[F,A,H],["Francis Lawrence"],["Keanu Reeves","Rachel Weisz","Shia LaBeouf"],7.0),
 ("Everything Everywhere All at Once",2022,[A,AD,S],["Daniel Kwan","Daniel Scheinert"],["Michelle Yeoh","Ke Huy Quan","Jamie Lee Curtis"],7.8),
 ("Nope",2022,[H,S,M],["Jordan Peele"],["Daniel Kaluuya","Keke Palmer","Steven Yeun"],6.8),
 ("Barbarian",2022,[H,T],["Zach Cregger"],["Georgina Campbell","Bill Skarsgård","Justin Long"],6.9),
 ("Weapons",2025,[H,M],["Zach Cregger"],["Julia Garner","Josh Brolin","Alden Ehrenreich"],7.4),
 ("The Substance",2024,[H,S,D],["Coralie Fargeat"],["Demi Moore","Margaret Qualley","Dennis Quaid"],7.1),
 ("Late Night with the Devil",2023,[H],["Cameron Cairnes","Colin Cairnes"],["David Dastmalchian","Laura Gordon","Ian Bliss"],6.9),
 ("Midsommar",2019,[H,D,M],["Ari Aster"],["Florence Pugh","Jack Reynor","Will Poulter"],7.1),
 ("In the Earth",2021,[H,S,T],["Ben Wheatley"],["Joel Fry","Ellora Torchia","Reece Shearsmith"],5.6),
 ("The Green Knight",2021,[F,AD,D],["David Lowery"],["Dev Patel","Alicia Vikander","Joel Edgerton"],6.6),
 ("Dune",2021,[S,AD],["Denis Villeneuve"],["Timothée Chalamet","Rebecca Ferguson","Oscar Isaac"],7.8),
 ("Oppenheimer",2023,[D,W],["Christopher Nolan"],["Cillian Murphy","Emily Blunt","Matt Damon"],8.1),
 ("Sunshine",2007,[S,T],["Danny Boyle"],["Cillian Murphy","Rose Byrne","Chris Evans"],7.1),
 ("Attack the Block",2011,[S,A,C],["Joe Cornish"],["John Boyega","Jodie Whittaker","Nick Frost"],6.6),
 ("The Fifth Element",1997,[S,A,AD],["Luc Besson"],["Bruce Willis","Milla Jovovich","Gary Oldman"],7.5),
 ("The City of Lost Children",1995,[F,S,AD],["Marc Caro","Jean-Pierre Jeunet"],["Ron Perlman","Daniel Emilfork","Judith Vittet"],7.3),
 ("Bubba Ho-Tep",2002,[C,H,F],["Don Coscarelli"],["Bruce Campbell","Ossie Davis"],6.6),
 ("John Dies at the End",2012,[C,H,S],["Don Coscarelli"],["Chase Williamson","Rob Mayes","Paul Giamatti"],5.9),
 ("My Name Is Bruce",2007,[C,H],["Bruce Campbell"],["Bruce Campbell","Grace Thurston","Ted Raimi"],5.8),
 ("Mad God",2021,[AN,H,F],["Phil Tippett"],["Alex Cox","Niketa Roman"],6.7),
 ("Hundreds of Beavers",2022,[C,AD],["Mike Cheslik"],["Ryland Brickson Cole Tews","Olivia Graves"],7.4),
 ("Dave Made a Maze",2017,[C,F,AD],["Bill Watterson"],["Nick Thune","Meera Rohit Kumbhani","Adam Busch"],6.1),
 ("Groundhog Day",1993,[C,F,R],["Harold Ramis"],["Bill Murray","Andie MacDowell","Chris Elliott"],7.7),
 ("The Nice Guys",2016,[C,CR,A],["Shane Black"],["Russell Crowe","Ryan Gosling","Angourie Rice"],7.1),
 ("Project Hail Mary",2026,[S,AD],["Phil Lord","Christopher Miller"],["Ryan Gosling","Sandra Hüller"],8.0),
 ("Phantom of the Paradise",1974,[C,H,F],["Brian De Palma"],["William Finley","Paul Williams","Jessica Harper"],7.0),
 ("Possession",1981,[H,D],["Andrzej Żuławski"],["Isabelle Adjani","Sam Neill","Heinz Bennent"],7.3),
 ("Suspiria",1977,[H],["Dario Argento"],["Jessica Harper","Stefania Casini","Alida Valli"],7.2),
]
out = [dict(id=f"sample-{i}", title=t, year=y, genres=g, directors=d, cast=c, rating=r)
       for i, (t, y, g, d, c, r) in enumerate(rows)]
p = pathlib.Path(__file__).with_name("sample_movies.json")
p.write_text(json.dumps({"sample": True, "movies": out}, ensure_ascii=False, indent=1))
print(len(out), "movies ->", p)
